//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace Catrobat.Models.v098 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class program {
        
        private header headerField;
        
        private @object[] objectListField;
        
        private programData dataField;
        
        private object settingsField;
        
        /// <remarks/>
        public header header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public @object[] objectList {
            get {
                return this.objectListField;
            }
            set {
                this.objectListField = value;
            }
        }
        
        /// <remarks/>
        public programData data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public object settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class header {
        
        private string applicationBuildNameField;
        
        private int applicationBuildNumberField;
        
        private string applicationNameField;
        
        private string applicationVersionField;
        
        private string catrobatLanguageVersionField;
        
        private string dateTimeUploadField;
        
        private string descriptionField;
        
        private string deviceNameField;
        
        private string landscapeModeField;
        
        private string mediaLicenseField;
        
        private string platformField;
        
        private string platformVersionField;
        
        private string programLicenseField;
        
        private string programNameField;
        
        private string remixOfField;
        
        private int screenHeightField;
        
        private string screenModeField;
        
        private int screenWidthField;
        
        private string tagsField;
        
        private string urlField;
        
        private string userHandleField;
        
        /// <remarks/>
        public string applicationBuildName {
            get {
                return this.applicationBuildNameField;
            }
            set {
                this.applicationBuildNameField = value;
            }
        }
        
        /// <remarks/>
        public int applicationBuildNumber {
            get {
                return this.applicationBuildNumberField;
            }
            set {
                this.applicationBuildNumberField = value;
            }
        }
        
        /// <remarks/>
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string applicationVersion {
            get {
                return this.applicationVersionField;
            }
            set {
                this.applicationVersionField = value;
            }
        }
        
        /// <remarks/>
        public string catrobatLanguageVersion {
            get {
                return this.catrobatLanguageVersionField;
            }
            set {
                this.catrobatLanguageVersionField = value;
            }
        }
        
        /// <remarks/>
        public string dateTimeUpload {
            get {
                return this.dateTimeUploadField;
            }
            set {
                this.dateTimeUploadField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        public string landscapeMode {
            get {
                return this.landscapeModeField;
            }
            set {
                this.landscapeModeField = value;
            }
        }
        
        /// <remarks/>
        public string mediaLicense {
            get {
                return this.mediaLicenseField;
            }
            set {
                this.mediaLicenseField = value;
            }
        }
        
        /// <remarks/>
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string platformVersion {
            get {
                return this.platformVersionField;
            }
            set {
                this.platformVersionField = value;
            }
        }
        
        /// <remarks/>
        public string programLicense {
            get {
                return this.programLicenseField;
            }
            set {
                this.programLicenseField = value;
            }
        }
        
        /// <remarks/>
        public string programName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
            }
        }
        
        /// <remarks/>
        public string remixOf {
            get {
                return this.remixOfField;
            }
            set {
                this.remixOfField = value;
            }
        }
        
        /// <remarks/>
        public int screenHeight {
            get {
                return this.screenHeightField;
            }
            set {
                this.screenHeightField = value;
            }
        }
        
        /// <remarks/>
        public string screenMode {
            get {
                return this.screenModeField;
            }
            set {
                this.screenModeField = value;
            }
        }
        
        /// <remarks/>
        public int screenWidth {
            get {
                return this.screenWidthField;
            }
            set {
                this.screenWidthField = value;
            }
        }
        
        /// <remarks/>
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string userHandle {
            get {
                return this.userHandleField;
            }
            set {
                this.userHandleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReferenceElemet {
        
        private string referenceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class formula {
        
        private formula leftChildField;
        
        private formula rightChildField;
        
        private string typeField;
        
        private string valueField;
        
        private string categoryField;
        
        /// <remarks/>
        public formula leftChild {
            get {
                return this.leftChildField;
            }
            set {
                this.leftChildField = value;
            }
        }
        
        /// <remarks/>
        public formula rightChild {
            get {
                return this.rightChildField;
            }
            set {
                this.rightChildField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetYBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTransparencyBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HideBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GoNStepsBackBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComeToFrontBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NextLookBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeVariableBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TurnLeftBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoopEndBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RepeatBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoopEndlessBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeYByNBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BroadcastBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IfLogicEndBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IfLogicElseBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StopAllSoundsBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GlideToBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointInDirectionBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IfLogicBeginBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WaitBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShowBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetVariableBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaceAtBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetSizeToBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoteBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeVolumeByNBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetVolumeToBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaySoundBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetLookBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetXBrick))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeverBrick))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetYBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetTransparencyBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HideBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoNStepsBackBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComeToFrontBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NextLookBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeVariableBrick : brick {
        
        private formula[] formulaListField;
        
        private bool inUserBrickField;
        
        private ReferenceElemet userVariableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
        
        /// <remarks/>
        public bool inUserBrick {
            get {
                return this.inUserBrickField;
            }
            set {
                this.inUserBrickField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceElemet userVariable {
            get {
                return this.userVariableField;
            }
            set {
                this.userVariableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TurnLeftBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoopEndBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RepeatBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoopEndlessBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeYByNBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BroadcastBrick : brick {
        
        private string broadcastMessageField;
        
        /// <remarks/>
        public string broadcastMessage {
            get {
                return this.broadcastMessageField;
            }
            set {
                this.broadcastMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IfLogicEndBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IfLogicElseBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopAllSoundsBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GlideToBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PointInDirectionBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IfLogicBeginBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WaitBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowBrick : brick {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetVariableBrick : brick {
        
        private formula[] formulaListField;
        
        private bool inUserBrickField;
        
        private ReferenceElemet userVariableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
        
        /// <remarks/>
        public bool inUserBrick {
            get {
                return this.inUserBrickField;
            }
            set {
                this.inUserBrickField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceElemet userVariable {
            get {
                return this.userVariableField;
            }
            set {
                this.userVariableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlaceAtBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSizeToBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoteBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeVolumeByNBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetVolumeToBrick : brick {
        
        private formula[] formulaListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlaySoundBrick : brick {
        
        private ReferenceElemet soundField;
        
        /// <remarks/>
        public ReferenceElemet sound {
            get {
                return this.soundField;
            }
            set {
                this.soundField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetLookBrick : brick {
        
        private ReferenceElemet lookField;
        
        /// <remarks/>
        public ReferenceElemet look {
            get {
                return this.lookField;
            }
            set {
                this.lookField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetXBrick : brick {
        
        private formula[] formulaListField;
        
        private bool isUserScriptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public formula[] formulaList {
            get {
                return this.formulaListField;
            }
            set {
                this.formulaListField = value;
            }
        }
        
        /// <remarks/>
        public bool isUserScript {
            get {
                return this.isUserScriptField;
            }
            set {
                this.isUserScriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeverBrick : brick {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WhenScript))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BroadcastScript))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StartScript))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class script {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhenScript : script {
        
        private brick[] brickListField;
        
        private string actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public brick[] brickList {
            get {
                return this.brickListField;
            }
            set {
                this.brickListField = value;
            }
        }
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BroadcastScript : script {
        
        private brick[] brickListField;
        
        private string receivedMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public brick[] brickList {
            get {
                return this.brickListField;
            }
            set {
                this.brickListField = value;
            }
        }
        
        /// <remarks/>
        public string receivedMessage {
            get {
                return this.receivedMessageField;
            }
            set {
                this.receivedMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartScript : script {
        
        private brick[] brickListField;
        
        private bool isUserScriptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public brick[] brickList {
            get {
                return this.brickListField;
            }
            set {
                this.brickListField = value;
            }
        }
        
        /// <remarks/>
        public bool isUserScript {
            get {
                return this.isUserScriptField;
            }
            set {
                this.isUserScriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sound {
        
        private string fileNameField;
        
        private string nameField;
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class look {
        
        private string fileNameField;
        
        private string nameField;
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class @object {
        
        private look[] lookListField;
        
        private sound[] soundListField;
        
        private script[] scriptListField;
        
        private object userBricksField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public look[] lookList {
            get {
                return this.lookListField;
            }
            set {
                this.lookListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public sound[] soundList {
            get {
                return this.soundListField;
            }
            set {
                this.soundListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public script[] scriptList {
            get {
                return this.scriptListField;
            }
            set {
                this.scriptListField = value;
            }
        }
        
        /// <remarks/>
        public object userBricks {
            get {
                return this.userBricksField;
            }
            set {
                this.userBricksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class programData {
        
        private object objectListOfListField;
        
        private object objectVariableListField;
        
        private object programListOfListsField;
        
        private object programVariableListField;
        
        private object userBrickVariableListField;
        
        /// <remarks/>
        public object objectListOfList {
            get {
                return this.objectListOfListField;
            }
            set {
                this.objectListOfListField = value;
            }
        }
        
        /// <remarks/>
        public object objectVariableList {
            get {
                return this.objectVariableListField;
            }
            set {
                this.objectVariableListField = value;
            }
        }
        
        /// <remarks/>
        public object programListOfLists {
            get {
                return this.programListOfListsField;
            }
            set {
                this.programListOfListsField = value;
            }
        }
        
        /// <remarks/>
        public object programVariableList {
            get {
                return this.programVariableListField;
            }
            set {
                this.programVariableListField = value;
            }
        }
        
        /// <remarks/>
        public object userBrickVariableList {
            get {
                return this.userBrickVariableListField;
            }
            set {
                this.userBrickVariableListField = value;
            }
        }
    }
}
