//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class program {
    
    private header headerField;
    
    private @object[] objectListField;
    
    private programData dataField;
    
    private object settingsField;
    
    /// <remarks/>
    public header header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public @object[] objectList {
        get {
            return this.objectListField;
        }
        set {
            this.objectListField = value;
        }
    }
    
    /// <remarks/>
    public programData data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public object settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class header {
    
    private string applicationBuildNameField;
    
    private int applicationBuildNumberField;
    
    private string applicationNameField;
    
    private string applicationVersionField;
    
    private string catrobatLanguageVersionField;
    
    private string dateTimeUploadField;
    
    private string descriptionField;
    
    private string deviceNameField;
    
    private string landscapeModeField;
    
    private string mediaLicenseField;
    
    private string platformField;
    
    private string platformVersionField;
    
    private string programLicenseField;
    
    private string programNameField;
    
    private string remixOfField;
    
    private int screenHeightField;
    
    private string screenModeField;
    
    private int screenWidthField;
    
    private string tagsField;
    
    private string urlField;
    
    private string userHandleField;
    
    /// <remarks/>
    public string applicationBuildName {
        get {
            return this.applicationBuildNameField;
        }
        set {
            this.applicationBuildNameField = value;
        }
    }
    
    /// <remarks/>
    public int applicationBuildNumber {
        get {
            return this.applicationBuildNumberField;
        }
        set {
            this.applicationBuildNumberField = value;
        }
    }
    
    /// <remarks/>
    public string applicationName {
        get {
            return this.applicationNameField;
        }
        set {
            this.applicationNameField = value;
        }
    }
    
    /// <remarks/>
    public string applicationVersion {
        get {
            return this.applicationVersionField;
        }
        set {
            this.applicationVersionField = value;
        }
    }
    
    /// <remarks/>
    public string catrobatLanguageVersion {
        get {
            return this.catrobatLanguageVersionField;
        }
        set {
            this.catrobatLanguageVersionField = value;
        }
    }
    
    /// <remarks/>
    public string dateTimeUpload {
        get {
            return this.dateTimeUploadField;
        }
        set {
            this.dateTimeUploadField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string deviceName {
        get {
            return this.deviceNameField;
        }
        set {
            this.deviceNameField = value;
        }
    }
    
    /// <remarks/>
    public string landscapeMode {
        get {
            return this.landscapeModeField;
        }
        set {
            this.landscapeModeField = value;
        }
    }
    
    /// <remarks/>
    public string mediaLicense {
        get {
            return this.mediaLicenseField;
        }
        set {
            this.mediaLicenseField = value;
        }
    }
    
    /// <remarks/>
    public string platform {
        get {
            return this.platformField;
        }
        set {
            this.platformField = value;
        }
    }
    
    /// <remarks/>
    public string platformVersion {
        get {
            return this.platformVersionField;
        }
        set {
            this.platformVersionField = value;
        }
    }
    
    /// <remarks/>
    public string programLicense {
        get {
            return this.programLicenseField;
        }
        set {
            this.programLicenseField = value;
        }
    }
    
    /// <remarks/>
    public string programName {
        get {
            return this.programNameField;
        }
        set {
            this.programNameField = value;
        }
    }
    
    /// <remarks/>
    public string remixOf {
        get {
            return this.remixOfField;
        }
        set {
            this.remixOfField = value;
        }
    }
    
    /// <remarks/>
    public int screenHeight {
        get {
            return this.screenHeightField;
        }
        set {
            this.screenHeightField = value;
        }
    }
    
    /// <remarks/>
    public string screenMode {
        get {
            return this.screenModeField;
        }
        set {
            this.screenModeField = value;
        }
    }
    
    /// <remarks/>
    public int screenWidth {
        get {
            return this.screenWidthField;
        }
        set {
            this.screenWidthField = value;
        }
    }
    
    /// <remarks/>
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string userHandle {
        get {
            return this.userHandleField;
        }
        set {
            this.userHandleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class formula {
    
    private formula leftChildField;
    
    private formula rightChildField;
    
    private string typeField;
    
    private string valueField;
    
    private string categoryField;
    
    /// <remarks/>
    public formula leftChild {
        get {
            return this.leftChildField;
        }
        set {
            this.leftChildField = value;
        }
    }
    
    /// <remarks/>
    public formula rightChild {
        get {
            return this.rightChildField;
        }
        set {
            this.rightChildField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SetXBrick))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeverBrick))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class brick {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SetXBrick : brick {
    
    private formula[] formulaListField;
    
    private bool isUserScriptField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public formula[] formulaList {
        get {
            return this.formulaListField;
        }
        set {
            this.formulaListField = value;
        }
    }
    
    /// <remarks/>
    public bool isUserScript {
        get {
            return this.isUserScriptField;
        }
        set {
            this.isUserScriptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ForeverBrick : brick {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StartScript))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class script {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StartScript : script {
    
    private brick[] brickListField;
    
    private bool isUserScriptField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public brick[] brickList {
        get {
            return this.brickListField;
        }
        set {
            this.brickListField = value;
        }
    }
    
    /// <remarks/>
    public bool isUserScript {
        get {
            return this.isUserScriptField;
        }
        set {
            this.isUserScriptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sound {
    
    private string fileNameField;
    
    private string nameField;
    
    /// <remarks/>
    public string fileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class look {
    
    private string fileNameField;
    
    private string nameField;
    
    /// <remarks/>
    public string fileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class @object {
    
    private look[] lookListField;
    
    private sound[] soundListField;
    
    private script[] scriptListField;
    
    private object userBricksField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public look[] lookList {
        get {
            return this.lookListField;
        }
        set {
            this.lookListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public sound[] soundList {
        get {
            return this.soundListField;
        }
        set {
            this.soundListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public script[] scriptList {
        get {
            return this.scriptListField;
        }
        set {
            this.scriptListField = value;
        }
    }
    
    /// <remarks/>
    public object userBricks {
        get {
            return this.userBricksField;
        }
        set {
            this.userBricksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class programData {
    
    private object objectListOfListField;
    
    private object objectVariableListField;
    
    private object programListOfListsField;
    
    private object programVariableListField;
    
    private object userBrickVariableListField;
    
    /// <remarks/>
    public object objectListOfList {
        get {
            return this.objectListOfListField;
        }
        set {
            this.objectListOfListField = value;
        }
    }
    
    /// <remarks/>
    public object objectVariableList {
        get {
            return this.objectVariableListField;
        }
        set {
            this.objectVariableListField = value;
        }
    }
    
    /// <remarks/>
    public object programListOfLists {
        get {
            return this.programListOfListsField;
        }
        set {
            this.programListOfListsField = value;
        }
    }
    
    /// <remarks/>
    public object programVariableList {
        get {
            return this.programVariableListField;
        }
        set {
            this.programVariableListField = value;
        }
    }
    
    /// <remarks/>
    public object userBrickVariableList {
        get {
            return this.userBrickVariableListField;
        }
        set {
            this.userBrickVariableListField = value;
        }
    }
}
